### ISSUE TITLE
dev-server这个分支起不来，

### ISSUE THREAD

**Issue by ghost** [Ma63d/kov-blog#3]
`报错，主要是const，let 的使用`

``` javaScript
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/study/kov-blog/server/controllers/token.js:8:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/study/kov-blog/server/controllers/index.js:4:15)
    at Module._compile (module.js:425:26)
Program node --harmony server/index.js exited with code 1

Starting child process with 'node --harmony server/index.js'
```

---

我的node环境是 : v5.1.1,
你在本地跑，这个可以不，除了这个项目，剩下的两个我可以跑起来

**Comment by Ma63d** [comment]
你好，我的node环境是6.2.1，能在本地跑起来。

实在是不好意思，因为我使用了大量的es6和es7语法，比如对象的解构赋值等等：
`const {articleArr,totalNumber} =yield {articleArr:...,totalNumber:...}`
所以可能需要较高版本（大于6.x）的node环境才能跑起来，可能需要nvm安装一下较高版本的node。

另外代码上面贴出来的这个bug是在5.x版本的node中不仅需要node --harmony 还需要在文件顶部加入`"use strict"`才能使用es6 新语法，但在6.x版本中不需要，所以导致代码跑不起来，但是即使所有使用es6语法的文件顶部都加入`"use strict"`，也会因为5.x版本不支持es7语法而导致代码跑不起来。

综上，麻烦你再安装一下6.x版本的node吧。
